# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR

reviews:
  profile: chill
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
  path_filters:
    - "!build/**"
    - "!**/*.bin"

chat:
  auto_reply: true
